# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a511f7edfb380eeccd2564c781a60969a51c70ef8c7f0ae32db56dd96dda13062e64c7ef7c96c97dcc72de8e5635391b727b50746167715139d8fdad45dd2c7

test:
  secret_key_base: 3b51cf13b3ff25701b0a4cd831e57c6386d8be333c0053149b92d7b9fd591d2d319a5f1aa4538728523dce1518b024f738a91c8e3f8a794bba7060691edb25ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
